name: PR Checks

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test_coverage:
    permissions: write-all
    name: Coverage report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          test-script: npm run test:coverage

  check:
    runs-on: ubuntu-22.04
    name: Code quality

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Run prettier
        run: npm run prettier:check

      - name: Run Typescript check
        run: npm run tscheck

      - name: Run linter
        run: npm run lint
