name: PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Code quality & Test
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          test-script: npm run test:coverage

      - name: Install dependencies
        run: npm ci

      - name: Run prettier
        run: npm run prettier:check

      - name: Run Typescript check
        run: npm run tscheck

      - name: Run linter
        run: npm run lint

      - name: Run Test
        run: npm run test