name: Test coverage

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test_coverage:
    permissions: write-all
    name: Coverage report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          test-script: npm run test:coverage